package blockchain

const (
	FuncPing = "ping"

	FuncCreateUser     = "CreateUser"
	FuncCreateReviewer = "CreateReviewer"
	FuncCreateAdmin    = "CreateAdmin"
	FuncCreatePaper    = "CreatePaper"

	FuncUpdateUserByEmail                  = "UpdateUserByEmail"
	FuncUpdateUserName                     = "UpdateUserName"
	FuncUpdateUserPassword                 = "UpdateUserPassword"
	FuncUpdateUserIsReviewer               = "UpdateUserIsReviewer"
	FuncUpdateUserIsNotReviewer            = "UpdateUserIsNotReviewer"
	FuncUpdateUserIsAdmin                  = "UpdateUserIsAdmin"
	FuncUpdateUserIsNotAdmin               = "UpdateUserIsNotAdmin"
	FuncUpdateUserReviewing                = "UpdateUserReviewing"
	FuncUpdatePaperById                    = "UpdatePaperById"
	FuncUpdatePeerReviewByPaperAndReviewer = "UpdatePeerReviewByPaperAndReviewer"

	FuncRetrieveUsers                     = "RetrieveUsers"
	FuncRetrieveUsersByName               = "RetrieveUsersByName"
	FuncRetrieveUsersIsReviewer           = "RetrieveUsersIsReviewer"
	FuncRetrieveUsersIsAdmin              = "RetrieveUsersIsAdmin"
	FuncRetrieveUsersByPaperId            = "RetrieveUsersByPaperId"
	FuncRetrieveUserByEmail               = "RetrieveUserByEmail"
	FuncRetrievePapers                    = "RetrievePapers"
	FuncRetrieveAcceptedPapers            = "RetrieveAcceptedPapers"
	FuncRetrieveRejectedPapers            = "RetrieveRejectedPapers"
	FuncRetrieveReviewingPapers           = "RetrieveReviewingPapers"
	FuncRetrieveAcceptedPapersByTitle     = "RetrieveAcceptedPapersByTitle"
	FuncRetrieveAcceptedPapersByAuthor    = "RetrieveAcceptedPapersByAuthor"
	FuncRetrieveAcceptedPapersByKeyword   = "RetrieveAcceptedPapersByKeyword"
	FuncRetrieveAcceptedPapersByUploader  = "RetrieveAcceptedPapersByUploader"
	FuncRetrieveRejectedPapersByUploader  = "RetrieveRejectedPapersByUploader"
	FuncRetrieveReviewingPapersByUploader = "RetrieveReviewingPapersByUploader"
	FuncRetrievePaperById                 = "RetrievePaperById"
	FuncRetrievePeerReviewsByReviewer     = "RetrievePeerReviewsByReviewer"
)
