version: '2'

networks:
  dl4csr:

services:

  cli.clayton-university.dl4csr.org:
    container_name: cli.clayton-university.dl4csr.org
    image: hyperledger/fabric-tools:1.4
    tty: true
    stdin_open: true
    environment:
      - CORE_PEER_ADDRESS=peer0.clayton-university.dl4csr.org:7051
      - CORE_PEER_ID=cli.clayton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=ClaytonUniversityMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clayton-university.dl4csr.org/users/Admin@clayton-university.dl4csr.org/msp
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org/tls/server.crt
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - GOPATH=/opt/gopath
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
    networks:
      - dl4csr

  cli.garyton-university.dl4csr.org:
    container_name: cli.garyton-university.dl4csr.org
    image: hyperledger/fabric-tools:1.4
    tty: true
    stdin_open: true
    environment:
      - CORE_PEER_ADDRESS=peer1.garyton-university.dl4csr.org:7051
      - CORE_PEER_ID=cli.garyton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=GarytonUniversityMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/garyton-university.dl4csr.org/users/Admin@garyton-university.dl4csr.org/msp
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org/tls/server.crt
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - GOPATH=/opt/gopath
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
    networks:
      - dl4csr