version: '2'

networks:
  dl4csr:

services:

  couchdb.clayton-university.dl4csr.org:
    container_name: couchdb.clayton-university.dl4csr.org
    image: hyperledger/fabric-couchdb:0.4
    environment:
      - COUCHDB_PASSWORD=clayton-university.dl4csr.org
      - COUCHDB_USER=ClaytonUniversity
      - GODEBUG=netdns=go
    ports:
      - "15984:5984"
    networks:
      - dl4csr

  couchdb.garyton-university.dl4csr.org:
    container_name: couchdb.garyton-university.dl4csr.org
    image: hyperledger/fabric-couchdb:0.4
    environment:
      - COUCHDB_PASSWORD=garyton-university.dl4csr.org
      - COUCHDB_USER=GarytonUniversity
      - GODEBUG=netdns=go
    ports:
      - "25984:5984"
    networks:
      - dl4csr