version: '2'

networks:
  dl4csr:

services:

  zookeeper1.dl4csr.org:
    container_name: zookeeper1.dl4csr.org
    hostname: zookeeper1.dl4csr.org
    image: hyperledger/fabric-zookeeper:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1.dl4csr.org:2888:3888 server.2=zookeeper2.dl4csr.org:2888:3888 server.3=zookeeper3.dl4csr.org:2888:3888
    ports:
      - "12181:2181"
      - "12888:2888"
      - "13888:3888"
    networks:
      - dl4csr

  zookeeper2.dl4csr.org:
    container_name: zookeeper2.dl4csr.org
    hostname: zookeeper2.dl4csr.org
    image: hyperledger/fabric-zookeeper:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1.dl4csr.org:2888:3888 server.2=zookeeper2.dl4csr.org:2888:3888 server.3=zookeeper3.dl4csr.org:2888:3888
    ports:
      - "22181:2181"
      - "22888:2888"
      - "23888:3888"
    networks:
      - dl4csr

  zookeeper3.dl4csr.org:
    container_name: zookeeper3.dl4csr.org
    hostname: zookeeper3.dl4csr.org
    image: hyperledger/fabric-zookeeper:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1.dl4csr.org:2888:3888 server.2=zookeeper2.dl4csr.org:2888:3888 server.3=zookeeper3.dl4csr.org:2888:3888
    ports:
      - "32181:2181"
      - "32888:2888"
      - "33888:3888"
    networks:
      - dl4csr