version: '2'

networks:
  dl4csr:

services:

  kafka1.dl4csr.org:
    container_name: kafka1.dl4csr.org
    hostname: kafka1.dl4csr.org
    image: hyperledger/fabric-kafka:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.dl4csr.org:2181,zookeeper2.dl4csr.org:2181,zookeeper3.dl4csr.org:2181
    ports:
      - "19092:9092"
    networks:
      - dl4csr

  kafka2.dl4csr.org:
    container_name: kafka2.dl4csr.org
    hostname: kafka2.dl4csr.org
    image: hyperledger/fabric-kafka:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.dl4csr.org:2181,zookeeper2.dl4csr.org:2181,zookeeper3.dl4csr.org:2181
    ports:
      - "29092:9092"
    networks:
      - dl4csr

  kafka3.dl4csr.org:
    container_name: kafka3.dl4csr.org
    hostname: kafka3.dl4csr.org
    image: hyperledger/fabric-kafka:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.dl4csr.org:2181,zookeeper2.dl4csr.org:2181,zookeeper3.dl4csr.org:2181
    ports:
      - "39092:9092"
    networks:
      - dl4csr

  kafka4.dl4csr.org:
    container_name: kafka4.dl4csr.org
    hostname: kafka4.dl4csr.org
    image: hyperledger/fabric-kafka:0.4
    restart: always
    environment:
      - GODEBUG=netdns=go
      - KAFKA_BROKER_ID=4
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.dl4csr.org:2181,zookeeper2.dl4csr.org:2181,zookeeper3.dl4csr.org:2181
    ports:
      - "49092:9092"
    networks:
      - dl4csr