version: '2'

networks:
  dl4csr:

services:

  zookeeper1.dl4csr.org:
    container_name: zookeeper1.dl4csr.org
    hostname: zookeeper1.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - dl4csr

  zookeeper2.dl4csr.org:
    container_name: zookeeper2.dl4csr.org
    hostname: zookeeper2.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=2
    ports:
      - "12181:2181"
      - "12888:2888"
      - "13888:3888"
    networks:
      - dl4csr

  zookeeper3.dl4csr.org:
    container_name: zookeeper3.dl4csr.org
    hostname: zookeeper3.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=3
    ports:
      - "22181:2181"
      - "22888:2888"
      - "23888:3888"
    networks:
      - dl4csr

  kafka1.dl4csr.org:
    container_name: kafka1.dl4csr.org
    hostname: kafka1.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper1.dl4csr.org
      - zookeeper2.dl4csr.org
      - zookeeper3.dl4csr.org
    ports:
      - "9092:9092"
    networks:
      - dl4csr

  kafka2.dl4csr.org:
    container_name: kafka2.dl4csr.org
    hostname: kafka2.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=2
    depends_on:
      - zookeeper1.dl4csr.org
      - zookeeper2.dl4csr.org
      - zookeeper3.dl4csr.org
    ports:
      - "19092:9092"
    networks:
      - dl4csr

  kafka3.dl4csr.org:
    container_name: kafka3.dl4csr.org
    hostname: kafka3.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=3
    depends_on:
      - zookeeper1.dl4csr.org
      - zookeeper2.dl4csr.org
      - zookeeper3.dl4csr.org
    ports:
      - "29092:9092"
    networks:
      - dl4csr

  kafka4.dl4csr.org:
    container_name: kafka4.dl4csr.org
    hostname: kafka4.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=4
    depends_on:
      - zookeeper1.dl4csr.org
      - zookeeper2.dl4csr.org
      - zookeeper3.dl4csr.org
    ports:
      - "39092:9092"
    networks:
      - dl4csr

  orderer.dl4csr.org:
    container_name: orderer.dl4csr.org
    image: hyperledger/fabric-orderer:1.4
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
#      - ORDERER_KAFKA_VERBOSE=true
#      - ORDERER_KAFKA_BROKERS=[kafka1.dl4csr.org:9092,kafka2.dl4csr.org:9092,kafka3.dl4csr.org:9092,kafka4.dl4csr.org:9092]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - "7050:7050"
    volumes:
      - ./channel-artifacts/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/dl4csr.org/orderers/orderer.dl4csr.org/:/etc/hyperledger/orderer
      - ./crypto-config/ordererOrganizations/dl4csr.org/orderers/orderer.dl4csr.org/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/dl4csr.org/orderers/orderer.dl4csr.org/tls:/var/hyperledger/orderer/tls
    networks:
      - dl4csr

  couchdb.clayton-university.dl4csr.org:
    container_name: couchdb.clayton-university.dl4csr.org
    image: hyperledger/fabric-couchdb:latest
    environment:
      - GODEBUG=netdns=go
      - COUCHDB_USER=ClaytonUniversity
      - COUCHDB_PASSWORD=clayton-university.dl4csr.org
    ports:
      - "5984:5984"
    networks:
      - dl4csr

  ca.clayton-university.dl4csr.org:
    container_name: ca.clayton-university.dl4csr.org
    image: hyperledger/fabric-ca:1.4
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.clayton-university.dl4csr.org
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.clayton-university.dl4csr.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${CLAYTON_UNIVERSITY_CA_PK}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/ca/ca.clayton-university.dl4csr.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/ca/${CLAYTON_UNIVERSITY_CA_PK}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca/ca.clayton-university.dl4csr.org-cert.pem --ca.keyfile /etc/hyperledger/ca/${CLAYTON_UNIVERSITY_CA_PK} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/ca/:/etc/hyperledger/ca
    networks:
      - dl4csr

  peer0.clayton-university.dl4csr.org:
    container_name: peer0.clayton-university.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.clayton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=ClaytonUniversityMSP
      - CORE_PEER_ADDRESS=peer0.clayton-university.dl4csr.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clayton-university.dl4csr.org:7051
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.clayton-university.dl4csr.org
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.clayton-university.dl4csr.org:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=ClaytonUniversity
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=clayton-university.dl4csr.org
    ports:
      - "7051:7051"
      - "7053:7053"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org:/etc/hyperledger/peer
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer0.clayton-university.dl4csr.org/tls:/var/hyperledger/tls
    depends_on:
      - orderer.dl4csr.org
      - couchdb.clayton-university.dl4csr.org
    networks:
      - dl4csr

  peer1.clayton-university.dl4csr.org:
    container_name: peer1.clayton-university.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.clayton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=ClaytonUniversityMSP
      - CORE_PEER_ADDRESS=peer1.clayton-university.dl4csr.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.clayton-university.dl4csr.org:7051
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.clayton-university.dl4csr.org
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.clayton-university.dl4csr.org:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=ClaytonUniversity
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=clayton-university.dl4csr.org
    ports:
      - "17051:7051"
      - "17053:7053"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer1.clayton-university.dl4csr.org:/etc/hyperledger/peer
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer1.clayton-university.dl4csr.org/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/peers/peer1.clayton-university.dl4csr.org/tls:/var/hyperledger/tls
    depends_on:
      - orderer.dl4csr.org
      - couchdb.clayton-university.dl4csr.org
    networks:
      - dl4csr

  cli.clayton-university.dl4csr.org:
    container_name: cli.clayton-university.dl4csr.org
    image: hyperledger/fabric-tools:1.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli.clayton-university.dl4csr.org
      - CORE_PEER_ADDRESS=peer0.clayton-university.dl4csr.org:7051
      - CORE_PEER_LOCALMSPID=ClaytonUniversityMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@clayton-university.dl4csr.org/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/peers/peer0.clayton-university.dl4csr.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/peers/peer0.clayton-university.dl4csr.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/peers/peer0.clayton-university.dl4csr.org/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: /bin/bash
    volumes:
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./channel-artifacts:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/clayton-university.dl4csr.org/:/etc/hyperledger/peer
      - ./crypto-config/ordererOrganizations/dl4csr.org/orderers/orderer.dl4csr.org/msp/tlscacerts/tlsca.dl4csr.org-cert.pem:/etc/hyperledger/orderer/tlsca/ca.pem
    depends_on:
      - orderer.dl4csr.org
      - peer0.clayton-university.dl4csr.org
      - couchdb.clayton-university.dl4csr.org
    networks:
      - dl4csr

  couchdb.garyton-university.dl4csr.org:
    container_name: couchdb.garyton-university.dl4csr.org
    image: hyperledger/fabric-couchdb:0.4
    environment:
      - GODEBUG=netdns=go
      - COUCHDB_USER=GarytonUniversity
      - COUCHDB_PASSWORD=garyton-university.dl4csr.org
    ports:
      - "6984:5984"
    networks:
      - dl4csr

  ca.garyton-university.dl4csr.org:
    container_name: ca.garyton-university.dl4csr.org
    image: hyperledger/fabric-ca:1.4
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.garyton-university.dl4csr.org
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.garyton-university.dl4csr.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${GARYTON_UNIVERSITY_CA_PK}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/ca/ca.garyton-university.dl4csr.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/ca/${GARYTON_UNIVERSITY_CA_PK}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca/ca.garyton-university.dl4csr.org-cert.pem --ca.keyfile /etc/hyperledger/ca/${GARYTON_UNIVERSITY_CA_PK} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/ca/:/etc/hyperledger/ca
    networks:
      - dl4csr

  peer0.garyton-university.dl4csr.org:
    container_name: peer0.garyton-university.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.garyton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=GarytonUniversityMSP
      - CORE_PEER_ADDRESS=peer0.garyton-university.dl4csr.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.garyton-university.dl4csr.org:7051
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.garyton-university.dl4csr.org
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.garyton-university.dl4csr.org:6984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=GarytonUniversity
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=garyton-university.dl4csr.org
    ports:
      - "27051:7051"
      - "27053:7053"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer0.garyton-university.dl4csr.org:/etc/hyperledger/peer
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer0.garyton-university.dl4csr.org/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer0.garyton-university.dl4csr.org/tls:/var/hyperledger/tls
    depends_on:
      - orderer.dl4csr.org
      - couchdb.garyton-university.dl4csr.org
    networks:
      - dl4csr

  peer1.garyton-university.dl4csr.org:
    container_name: peer1.garyton-university.dl4csr.org
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.garyton-university.dl4csr.org
      - CORE_PEER_LOCALMSPID=GarytonUniversityMSP
      - CORE_PEER_ADDRESS=peer1.garyton-university.dl4csr.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.garyton-university.dl4csr.org:7051
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.garyton-university.dl4csr.org
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.garyton-university.dl4csr.org:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=GarytonUniversity
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=garyton-university.dl4csr.org
    ports:
      - "37051:7051"
      - "37053:7053"
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org:/etc/hyperledger/peer
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/peers/peer1.garyton-university.dl4csr.org/tls:/var/hyperledger/tls
    depends_on:
      - orderer.dl4csr.org
      - couchdb.garyton-university.dl4csr.org
    networks:
      - dl4csr

  cli.garyton-university.dl4csr.org:
    container_name: cli.garyton-university.dl4csr.org
    image: hyperledger/fabric-tools:1.4
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli.garyton-university.dl4csr.org
      - CORE_PEER_ADDRESS=peer1.garyton-university.dl4csr.org:7051
      - CORE_PEER_LOCALMSPID=GarytonUniversityMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@garyton-university.dl4csr.org/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/peers/peer1.garyton-university.dl4csr.org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/peers/peer1.garyton-university.dl4csr.org/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/peers/peer1.garyton-university.dl4csr.org/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: /bin/bash
    volumes:
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./channel-artifacts:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/garyton-university.dl4csr.org/:/etc/hyperledger/peer
      - ./crypto-config/ordererOrganizations/dl4csr.org/orderers/orderer.dl4csr.org/msp/tlscacerts/tlsca.dl4csr.org-cert.pem:/etc/hyperledger/orderer/tlsca/ca.pem
    depends_on:
      - orderer.dl4csr.org
      - peer1.garyton-university.dl4csr.org
      - couchdb.garyton-university.dl4csr.org
    networks:
      - dl4csr